#!/bin/bash

#Version number
versionnmb="v1.7.7"

echo -e "\n\e[35mGMCALC ${versionnmb}\e[0m\n"

if [ $1 = "--help" ]; then
   echo -e "GMCALC is a program in BASH SHELL designed to make life easier \nbetween Gaussview, Gaussian and MOPAC programs.\n"
   echo -e "Commands are as follow:"
   echo -e "\t$0 --check \tCheck files."
   echo -e "\t$0 --init \tInitialize the program."
   echo -e "\t$0 --reset\tReset the program."
   echo -e "\t$0 --lqta \tConfiguration for LQTA students."
   echo -e "\nGeneral:\n\t$0 [--startup_option] [molecule [method_for_gaussian [method_for_mopac] ] ]\n"
   exit
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function bin_chk {
    if [ -f $1 ]; then
      echo -e "File $1 OK"
    else  
      echo -e "File $1 does not exist"
      files_missing=true
    fi
    sleep 0.01
}

echo -e "Checking files.\n"
sleep 0.01
binfiles=("config.sh")
binfiles+=("bin/menu/menu.sh" "bin/menu/menuopts.sh")
binfiles+=("bin/prgmscr/gauss.sh" "bin/prgmscr/mopac.sh")
binfiles+=("bin/fnct/state.sh" "bin/fnct/chkst.sh" "bin/fnct/sev.sh" "bin/fnct/ask.sh" "bin/fnct/other.sh" "bin/fnct/checkfld.sh")
binfiles+=("bin/init/init.sh")
binfiles+=("bin/main.sh")

for binfile in "${binfiles[@]}"
do
  bin_chk ${DIR}/${binfile}
done

for ini in opt_ini.sh .default_config.sh .lqta_config.sh
do
  bin_chk ${DIR}/bin/init/${ini}
done


if [ $files_missing ]; then
  echo -e "\n\e[31mERROR\e[0m. Some files are missing, please install again.\n"
  exit
else
  echo -e "\nCheck SUCCESS. All correct.\n"
  sleep 0.02
fi

if [ $1 = "--check" ]; then
    exit
fi

source ${DIR}/bin/init/opt_ini.sh

for binfile in "${binfiles[@]}"
do
  source ${DIR}/${binfile}
done

